name: Kilted Build
# author: Christoph Froehlich <christoph.froehlich@ait.ac.at>
# description: 'Build the stack.'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/kilted-build.yml'
      - 'ros_controls.kilted.repos'
      - 'ros2_control_cmake/**'
  push:
    branches:
      - master

jobs:
  stack-build:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-industrial-ci-with-cache.yml@master
    with:
      ros_distro: kilted
      ros_repo: testing
      ref_for_scheduled_build: master
